export const products = [
    { id: 1, 
        name: 'Black Geometric Cardigan', 
        images: [
            '../img/BlackCardiganFront.jpg',
            '../img/BlackCardiganBack.jpg'
        ],
        notes: "",
        available: "Custom Order Only",
        type: 'Clothes', 
        price: "Priced on Order",
    },
    { id: 2, 
        name: 'Blue Flower Cardigan', 
        images: [
            '../img/BlueCardiganFront.jpg',
            '../img/BlueCardiganBack.jpg'
        ],
        notes: "",
        available: "Custom Order Only",
        type: 'Clothes', 
        price: "Priced on Order",
    },
    { id: 3, 
        name: 'Purple Cardigan', 
        images: [
            '../img/PurpleCardiganFront.jpg',
            '../img/PurpleCardiganBack.jpg'
        ],
        notes: "",
        available: "Custom Order Only",
        type: 'Clothes', 
        price: "Priced on Order",
    },
    { id: 4, 
        name: 'Coloured Geometric Cardigan', 
        images: [
            '../img/ColouredCardiganFront.jpg',
            '../img/ColouredCardiganBack.jpg'
        ],
        notes: "",
        available: "Custom Order Only",
        type: 'Clothes', 
        price: "Priced on Order",
    },
    { id: 5, 
        name: 'Dragon Scale Dice Bag', 
        images: [
            '../img/RainbowDragonScaleDiceBagSide.jpg',
            '../img/RainbowDragonScaleDiceBagBottom.jpg'
        ],
        notes: " ~ 8cm x 9cm ,  Upcycled Leather Base",
        available: "Yes!",
        type: 'Bags', 
        price: "$25",
    },
    { id: 6, 
        name: 'Large Dragon Scale Dice Bag', 
        images: [
            '../img/PurpleBluePinkDragonScaleDiceBagSide.jpg',
        ],
        notes: " ~ 8cm x 9cm ,  Upcycled Leather Base",
        available: "Yes!",
        type: 'Bags', 
        price: "$25",
    },
    { id: 7, 
        name: 'Forget Me Not Earrings', 
        images: [
            '../img/AmazonPhotos/ForgetMeNotEarrings.jpg',
        ],
        notes: " Lobster Not Included",
        available: "Yes!",
        type: 'Earrings', 
        price: "$25",
    },
    { id: 8, 
        name: 'Boo-tiful Earrings', 
        images: [
            '../img/AmazonPhotos/Boo-tifulEarrings.jpg',
        ],
        notes: "Glow in the dark Ghost earrings",
        available: "Yes!",
        type: 'Earrings', 
        price: "$35",
    },
    { id: 9, 
        name: 'Rain Brings Rainbows Earrings', 
        images: [
            '../img/AmazonPhotos/RainBringsRainbowsEarrings.jpg',
        ],
        notes: "",
        available: "Yes!",
        type: 'Earrings', 
        price: "$25",
    },
    { id: 10, 
        name: 'Granny Too Hip to Be Square', 
        images: [
            '../img/AmazonPhotos/GrannyTooHipEarrings.jpg',
        ],
        notes: "",
        available: "Yes!",
        type: 'Earrings', 
        price: "$25",
    },
    { id: 11, 
        name: 'WitchHat', 
        images: [
            '../img/AmazonPhotos/WitchHat.jpg',
            '../img/AmazonPhotos/WitchHat1.jpg'
        ],
        notes: "",
        available: "Custom Order Only",
        type: 'Clothes', 
        price: "Priced on Order",
    },
    { id: 12, 
        name: 'Sun And Moon Earrings', 
        images: [
            '../img/AmazonPhotos/SunAndMoonEarrings.jpg',
            '../img/AmazonPhotos/SunAndMoonEarrings1.jpg',
            '../img/AmazonPhotos/SunAndMoonEarrings2.jpg'    
        ],
        notes: "",
        available: "Custom Order Only",
        type: 'Earrings', 
        price: "Priced on Order",
    },
    { id: 13, 
        name: 'Cherry Earrings', 
        images: [
            '../img/AmazonPhotos/SingleCherryEarrings.jpg'   
        ],
        notes: "",
        available: "Custom Order Only",
        type: 'Earrings', 
        price: "Priced on Order",
    },
    { id: 14, 
        name: 'Bookmarks', 
        images: [
            '../img/AmazonPhotos/RocketBookmark.jpg' ,
            '../img/AmazonPhotos/RocketBookmark1.jpg' ,
            '../img/AmazonPhotos/ShipBookmark.jpg' ,
            '../img/AmazonPhotos/ShipBookmark2.jpg' ,
            '../img/AmazonPhotos/ShipBookmark3.jpg' ,
            '../img/AmazonPhotos/JellyBookmark2.jpg' ,
            '../img/AmazonPhotos/JellyBookmark3.jpg' ,
            '../img/AmazonPhotos/KittyBookmark.jpg' ,
            '../img/AmazonPhotos/KittyBookmark2.jpg' ,

        ],
        notes: "Available as Rocket, Boat, Jellyfish, or Kitty",
        available: "Custom Order Only",
        type: 'Decor', 
        price: "Priced on Order",
    },
];
